version: 2.1

defaults: &defaults
  docker:
    - image: cimg/python:3.11
  working_directory: ~/project

prepare_venv: &prepare_venv
  run:
    name: Create venv
    command: |
      python3 -m venv venv
      source venv/bin/activate
      pip install --upgrade pip

prepare_tox: &prepare_tox
  run:
    name: Install tox
    command: |
      pip install tox

jobs:
  test_app:
    <<: *defaults
    working_directory: ~/project/house_prices_api
    steps:
      - checkout:
          path: ~/project
      - *prepare_tox
      - run:
          name: Run FastAPI app tests
          command: |
            tox

  test_model_package:
    <<: *defaults
    working_directory: ~/project/model_package
    steps:
      - checkout:
          path: ~/project
      - *prepare_tox
      - run:
          name: Run model package tests
          command: |
            tox

  deploy_app:
    <<: *defaults
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Deploy to Render
          command: |
            curl -X POST \
              -H "Authorization: Bearer $RENDER_API_KEY" \
              -H "Content-Type: application/json" \
              -d '{}' \
              https://api.render.com/deploy/srv-xxxxxxxxxxxxxxxxx

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test_model_package
      - test_app:
          requires:
            - test_model_package
      - deploy_app:
          requires:
            - test_app
          filters:
            branches:
              only: master
